### ISSUE TITLE
Visualise the recorded data with mEPSPs as well as other spikes, option to pick up the number of spikes with thresholding.  

### ISSUE THREAD

**Issue by anzalks** [anzalks/Ephys_analysis#1]
The .DAT file uploaded is a recorded data sample. it contains a time series data set.

**Comment by dilawar** [comment]
What format is `1.dat` file?

**Comment by dilawar** [comment]
I've add `README.md` file which explains how to launch the application to do the analysis using `ephyview` https://github.com/NeuralEnsemble/ephyviewer

**Comment by dilawar** [comment]
I have very basic analysis script. I can add other methods you want as well. When you have couple of hours to spares, ping me.
